accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
]

cars/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cars, name='cars'),
    path('<int:id>', views.car_detail, name='car_detail'),
    path('search', views.search, name='search'),
]

carzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cars/', include('cars.urls')),
   
    path('marbles/', include('marbles.urls')),
    path('marblecontacts/', include('marblecontacts.urls')),    

    path('tiles/', include('tiles.urls')),
    path('tilecontacts/', include('tilecontacts.urls')),    
    
    path('store/', include('store.urls')),

    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.store, name="store"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),

    #URL for Products
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),

    
]

accounts/models.py
from django.db import models

# Create your models here.

store/forms.py
from django.contrib.auth import password_validation
from store.models import Address
from django import forms
import django
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.db import models
from django.db.models import fields
from django.forms import widgets
from django.forms.fields import CharField
from django.utils.translation import gettext, gettext_lazy as _



class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password'}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        labels = {'email': 'Email'}
        widgets = {'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Username'})}


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['locality', 'city', 'state']
        widgets = {'locality':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Popular Place like Restaurant, Religious Site, etc.'}), 'city':forms.TextInput(attrs={'class':'form-control', 'placeholder':'City'}), 'state':forms.TextInput(attrs={'class':'form-control', 'placeholder':'State or Province'})}


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Old Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'auto-focus':True, 'class':'form-control', 'placeholder':'Current Password'}))
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control', 'placeholder':'New Password'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control', 'placeholder':'Confirm Password'}))


class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label=_("Email"), max_length=254, widget=forms.EmailInput(attrs={'autocomplete':'email', 'class':'form-control'}))


class SetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password','class':'form-control'}))

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from contacts.models import Contact
from django.contrib.auth.decorators import login_required

# Create your views here.

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('login')
    return render(request, 'accounts/login.html')

def register(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email already exists!')
                    return redirect('register')
                else:
                    user = User.objects.create_user(first_name=firstname, last_name=lastname, email=email, username=username, password=password)
                    auth.login(request, user)
                    messages.success(request, 'You are now logged in.')
                    return redirect('dashboard')
                    user.save()
                    messages.success(request, 'You are registered successfully.')
                    return redirect('login')
        else:
            messages.error(request, 'Password do not match')
            return redirect('register')
    else:
        return render(request, 'accounts/register.html')


@login_required(login_url = 'login')
def dashboard(request):
    user_inquiry = Contact.objects.order_by('-create_date').filter(user_id=request.user.id)
    # count = Contact.objects.order_by('-create_date').filter(user_id=request.user.id).count()

    data = {
        'inquiries': user_inquiry,
    }
    return render(request, 'accounts/dashboard.html', data)

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')
    return redirect('home')

store/views.py
import django
from django.contrib.auth.models import User
from store.models import Address, Cart, Category, Order, Product
from django.shortcuts import redirect, render, get_object_or_404
from .forms import RegistrationForm, AddressForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator # for Class Based Views


# Create your views here.

def store(request):
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    context = {
        'categories': categories,
        'products': products,
    }
    return render(request, 'store/store.html', context)


def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)
    context = {
        'product': product,
        'related_products': related_products,

    }
    return render(request, 'store/detail.html', context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True)
    return render(request, 'store/categories.html', {'categories':categories})


def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)
    categories = Category.objects.filter(is_active=True)
    context = {
        'category': category,
        'products': products,
        'categories': categories,
    }
    return render(request, 'store/category_products.html', context)


# Authentication Starts Here

class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'account/register.html', {'form': form})
    
    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            messages.success(request, "Congratulations! Registration Successful!")
            form.save()
        return render(request, 'account/register.html', {'form': form})
        

@login_required
def profile(request):
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'account/profile.html', {'addresses':addresses, 'orders':orders})


@method_decorator(login_required, name='dispatch')
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, 'account/add_address.html', {'form': form})

    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            user=request.user
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            reg = Address(user=user, locality=locality, city=city, state=state)
            reg.save()
            messages.success(request, "New Address Added Successfully.")
        return redirect('store:profile')


@login_required
def remove_address(request, id):
    a = get_object_or_404(Address, user=request.user, id=id)
    a.delete()
    messages.success(request, "Address removed.")
    return redirect('store:profile')

@login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)

    # Check whether the Product is alread in Cart or Not
    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    if item_already_in_cart:
        cp = get_object_or_404(Cart, product=product_id, user=user)
        cp.quantity += 1
        cp.save()
    else:
        Cart(user=user, product=product).save()
    
    return redirect('store:cart')


@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # Display Total on Cart Page
    amount = decimal.Decimal(0)
    shipping_amount = decimal.Decimal(10)
    # using list comprehension to calculate total amount based on quantity and shipping
    cp = [p for p in Cart.objects.all() if p.user==user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    # Customer Addresses
    addresses = Address.objects.filter(user=user)

    context = {
        'cart_products': cart_products,
        'amount': amount,
        'shipping_amount': shipping_amount,
        'total_amount': amount + shipping_amount,
        'addresses': addresses,
    }
    return render(request, 'store/cart.html', context)


@login_required
def remove_cart(request, cart_id):
    if request.method == 'GET':
        c = get_object_or_404(Cart, id=cart_id)
        c.delete()
        messages.success(request, "Product removed from Cart.")
    return redirect('store:cart')


@login_required
def plus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        cp.quantity += 1
        cp.save()
    return redirect('store:cart')


@login_required
def minus_cart(request, cart_id):
    if request.method == 'GET':
        cp = get_object_or_404(Cart, id=cart_id)
        # Remove the Product if the quantity is already 1
        if cp.quantity == 1:
            cp.delete()
        else:
            cp.quantity -= 1
            cp.save()
    return redirect('store:cart')


@login_required
def checkout(request):
    user = request.user
    address_id = request.GET.get('address')
    
    address = get_object_or_404(Address, id=address_id)
    # Get all the products of User in Cart
    cart = Cart.objects.filter(user=user)
    for c in cart:
        # Saving all the products from Cart to Order
        Order(user=user, address=address, product=c.product, quantity=c.quantity).save()
        # And Deleting from Cart
        c.delete()
    return redirect('store:orders')


@login_required
def orders(request):
    all_orders = Order.objects.filter(user=request.user).order_by('-ordered_date')
    return render(request, 'store/orders.html', {'orders': all_orders})





def shop(request):
    return render(request, 'store/shop.html')





def test(request):
    return render(request, 'store/test.html')

templates/store/account/add_address.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        <h1 class="mb-5">Add New Address</h1>
        
        
        <div class="card mb-4" id="forms">
          <div class="card-header">
            <small>
            With a this account, you can save time during checkout, access your shopping bag from any device and view your order history.
            </small>
          </div>
          <div class="card-body">

            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                    </p>
                {% endfor %}
              {% endif %}

            </form>

            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/login.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        <h1 class="mb-5">Log In to Your Account</h1>
        
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
              
            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Login</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </p>
                {% endfor %}
              {% endif %}


            </form>

            <hr>

            Forgot Password? <a href="{% url 'store:password-reset' %}">Reset Now</a> <br>
            New Member? <a href="{% url 'store:register' %}">Create an Account</a> 
            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/password_change.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        <h1 class="mb-5">Change Your Password</h1>
        
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
              
            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Save</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </p>
                {% endfor %}
              {% endif %}


            </form>

            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/password_change_done.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        {% comment %} <h1 class="mb-5">Password Changed</h1> {% endcomment %}
        
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
           
            <h1>Your Password Changed Successfully.</h1>
            
            <div class="text-center">
                Let's <a href="{% url 'store:profile' %}"> go to Profile.</a>
            </div>
            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/password_reset.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        <h1 class="mb-5">Password Reset</h1>
        <p class="text-secondary">Add your Email Address to get password reset link.</p>
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
              
            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </p>
                {% endfor %}
              {% endif %}


            </form>

            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        {% comment %} <h1 class="mb-5">Password Changed</h1> {% endcomment %}
        
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
           
            <h1>New Password Set Successfully.</h1>
            
            <div class="text-center">
              Let's <a href="{% url 'store:login' %}"> Login.</a>
            </div>
            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        <h1 class="mb-5">Set Password</h1>
        <p class="text-secondary">Set new password here.</p>
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
              
            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Save</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">
                        {{error}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </p>
                {% endfor %}
              {% endif %}


            </form>

            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        {% comment %} <h1 class="mb-5">Password Changed</h1> {% endcomment %}
        
        
        <div class="card mb-4" id="forms">
          
          <div class="card-body">
           
            <h1>Email Sent Successfully.</h1>
            
            <div>
              Please Check your inbox for the password reset link.
            </div>
            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}

templates/store/account/register.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}

      <div class="container py-5">
        <div class="col-md-8 offset-2">

        <h1 class="mb-5">Create Your Account</h1>
        
        
        <div class="card mb-4" id="forms">
          <div class="card-header">
            <small>
            With a this account, you can save time during checkout, access your shopping bag from any device and view your order history.
            </small>
          </div>
          <div class="card-body">

            {% include 'partials/_messages.html' %}

            <form method="post" action="">
              <fieldset>
                {% csrf_token %}

                {% for fm in form %}
                    <div class="form-group">
                        {{fm.label_tag}}
                        {{fm}}
                        <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
              </fieldset>

              {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger alert-dismissible fade show" role="alert" my-3">
                        {{error}}
                    </p>
                {% endfor %}
              {% endif %}

            </form>

            <hr>

            Already have an account? <a href="{% url 'store:login' %}">Log In </a>
            
          </div>
        </div>

        </div>       
      </div>
{% endblock content %}